# Generated by Django 3.2.7 on 2022-05-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=254)),
                ('Roll', models.CharField(max_length=256)),
                ('Phone', models.IntegerField()),
                ('Dept', models.CharField(max_length=256)),
                ('SubC', models.BooleanField()),
                ('SubS', models.BooleanField()),
                ('SubE', models.BooleanField()),
                ('SubA', models.BooleanField()),
                ('SubP', models.BooleanField()),
                ('Comments', models.CharField(max_length=256)),
            ],
        ),
    ]
